### ISSUE TITLE
No podspec found error when compiling iOS project using whisper_flutter

### ISSUE THREAD

**Issue by zhdhr0000** [azkadev/whisper_dart#16]
Hello, thank you very much for providing whisper_dart and whisper_flutter. 
When I tried to compile for iOS using flutter build ios, I encountered an error. 
The error output is as follows (some seemingly irrelevant content has been removed):

```
Running pod install...                                             829ms
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      A whisper_flutter
      - Flutter
      - audioplayers_darwin
       ......
      - url_launcher_ios

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `audioplayers_darwin` from `.symlinks/plugins/audioplayers_darwin/ios`
       ......
    -> Fetching podspec for `url_launcher_ios` from `.symlinks/plugins/url_launcher_ios/ios`
    -> Fetching podspec for `whisper_flutter` from `.symlinks/plugins/whisper_flutter/ios`
    [!] No podspec found for `whisper_flutter` in `.symlinks/plugins/whisper_flutter/ios`


    /usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/external_sources/path_source.rb:14:in `block in fetch'
    /usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/external_sources/path_source.rb:11:in `fetch'
    /usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:993:in `fetch_external_source'
    /usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:972:in `block (2 levels) in fetch_external_sources'
    /usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:971:in `each'
    /usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:971:in `block in fetch_external_sources'
    /usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:970:in `fetch_external_sources'
    /usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:117:in `analyze'
    /usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:416:in `analyze'
    /usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies'
    /usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
    /usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:161:in `install!'
    /usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
    /usr/local/lib/ruby/gems/3.2.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
    /usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
    /usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
    /usr/local/opt/ruby/bin/pod:25:in `load'
    /usr/local/opt/ruby/bin/pod:25:in `<main>'

Error running pod install
```

I think there may be something wrong with the configuration of the podspec. After checking the relevant code, I noticed that the podspec file should be this file: 
```package/whisper_flutter/ios/whisper_dart.podspec``` 
which describes the pod name as ```whisper_flutter```, but the name of this file is ```whisper_dart.podspec```. 
Perhaps this is the reason for the error.

**Comment by ibrahimdevs** [comment]
I created a pull request for this @JeisonSanches @azkadev https://github.com/azkadev/whisper_dart/pull/17
