### ISSUE TITLE
How to use whisper_dart or whisper_flutter for a Flutter app in Windows and then for Android?

### ISSUE THREAD

**Issue by yubrshen** [azkadev/whisper_dart#9]
Thank you for providing whisper_dart and whisper_flutter!
I'm new to Flutter app development. I just finished the tutorial to create a new "Hello World" Flutter app with VS Code.
Could you please give me more instructions?

So far, I'm copying the example with whisper_flutter (found at https://pub.dev/packages/whisper_flutter/example), for lib\main.dart, but got errors probably with the following lines:
` WidgetsFlutterBinding.ensureInitialized();
  DynamicLibrary.open("libwhisper.so");`

but I got the following errors:
`Launching lib\main.dart on Windows in debug mode...
main.dart:1
LINK : fatal error LNK1149: output filename matches input filename 'C:\Users\yubrs\dev_windows\whisper_flutter_example\build\windows\plugins\whisper_flutter\shared\Debug\whisper.lib' [C:\Users\yubrs\dev_windows\whisper_flutter_example\build\windows\plugins\whisper_flutter\shared\whisper_flutter.vcxproj]
Exception: Build process failed.
Exited (sigterm)`

I suspect that besides copying the example code, I might need to do more setup in my project for the app.
But what should I do? Thanks for your help!

**Comment by JackZhang1994** [comment]
E/flutter (  749): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library '/libwhisper.so': dlopen failed: library "/libwhisper.so" not found
E/flutter (  749): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
E/flutter (  749): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
E/flutter (  749): #2      main (package:example/main.dart:20:18)
E/flutter (  749): #3      _runMain.<anonymous closure> (dart:ui/hooks.dart:131:23)
E/flutter (  749): #4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
E/flutter (  749): #5      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
E/flutter (  749): 

The same error when launch lib\main.dart on Android Device in debug mode...
